name: Tests

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/ci.yml
      - bot/**
      - tests/bot/**

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r bot/requirements.txt
          pip install -r tests/bot/requirements.txt

      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          export PYTHONPATH=$(pwd)
          pytest ./tests/bot/
